"""Generate task5_restoration.json with 15 episodes."""
import json, random, os

OCR_MAP = {'ā':'a','ī':'i','ū':'u','ṭ':'t','ḍ':'d','ṣ':'s','ś':'s','ṃ':'m','ḥ':'h','ṇ':'n','ṛ':'r','ḷ':'l'}

def ocr_noise(text, level, seed):
    rng = random.Random(seed)
    return "".join(OCR_MAP[c] if c in OCR_MAP and rng.random() < level else c for c in text)

DIFF = [
    {"d":"beginner","noise":0.0,"budget":8,"commentary_pct":1.0,"witnesses":0},
    {"d":"intermediate","noise":0.1,"budget":6,"commentary_pct":0.5,"witnesses":1},
    {"d":"hard","noise":0.25,"budget":5,"commentary_pct":0.3,"witnesses":2},
    {"d":"expert","noise":0.4,"budget":4,"commentary_pct":0.0,"witnesses":2},
]

EPISODES_RAW = [
    {"id":"rest_001","diff":0,"source":"Bhagavad Gita 2.19","domain":"philosophy","ptype":"glossary",
     "iast":"ya enaṃ vetti hantāraṃ yaś cainaṃ manyate hatam","dev":"य एनं वेत्ति हन्तारं यश्चैनं मन्यते हतम्",
     "gloss":"He who thinks this Self is a slayer and he who thinks it is slain",
     "correct":"The Self neither slays nor is it slain — 'hantāram' refers to the agent of action, not the true subject",
     "partial":["The verse concerns action and non-action"],"partial_idx":[2],
     "tools_needed":["lexicon_lookup","commentary_fetch"],
     "options":["The Self neither slays nor is it slain — 'hantāram' refers to the agent of action, not the true subject",
                "The verse describes physical combat and the ethics of killing",
                "The verse concerns action and non-action",
                "Both slaying and being slain are valid interpretations depending on context"],
     "glossary":{"hantāram":[{"meaning":"slayer, one who kills","domain":"general","confidence":0.9},
                              {"meaning":"agent of action (philosophical sense)","domain":"vedanta","confidence":0.95}]},
     "sandhi":{"yaścainaṃ":[{"split":"yaś ca enaṃ","rule":"visarga sandhi + vowel coalescence","plausibility_score":0.95},
                             {"split":"yaś cai naṃ","rule":"invalid split","plausibility_score":0.05}]},
     "meter":{"yaś ca enaṃ":{"preserves_meter":True,"meter_name":"anuṣṭubh"},
              "yaś cai naṃ":{"preserves_meter":False,"meter_name":None}},
     "commentary":{"hantāram":"Śaṅkarācārya: 'hantā' here refers to the buddhi, the apparent agent, not the ātman",
                    "2.19":"This verse establishes the doctrine of ātman as akartā — the non-doer"},
     "witness":{},"entity":{"enaṃ":["ātman (Self)","śarīra (body)"],"yaḥ":["the one who knows"]}},

    {"id":"rest_002","diff":0,"source":"Sushruta Samhita 1.15","domain":"ayurveda","ptype":"glossary",
     "iast":"agniḥ sarvaṃ pacati dhātuṣu","dev":"अग्निः सर्वं पचति धातुषु",
     "gloss":"Agni digests everything in the bodily tissues",
     "correct":"'agniḥ' refers to the digestive fire (jaṭharāgni) that transforms nutrients within the seven dhātus",
     "partial":["Agni here means the general element of fire"],"partial_idx":[1],
     "tools_needed":["lexicon_lookup","commentary_fetch"],
     "options":["'agniḥ' refers to the digestive fire (jaṭharāgni) that transforms nutrients within the seven dhātus",
                "Agni here means the general element of fire",
                "The verse describes ritual fire offerings",
                "Agni refers to inflammation in the tissues"],
     "glossary":{"agniḥ":[{"meaning":"digestive fire (jaṭharāgni)","domain":"ayurveda","confidence":0.95},
                           {"meaning":"fire element","domain":"general","confidence":0.7}]},
     "sandhi":{},"meter":{},"commentary":{"agniḥ":"Dalhana: agni here is specifically jaṭharāgni"},
     "witness":{},"entity":{"agniḥ":["jaṭharāgni","bhūtāgni"]}},

    {"id":"rest_003","diff":0,"source":"Ramayana 2.34","domain":"narrative","ptype":"coherence",
     "iast":"sa rāmaḥ pitaraṃ natvā vanaṃ jagāma","dev":"स रामः पितरं नत्वा वनं जगाम",
     "gloss":"That Rama, having bowed to his father, went to the forest",
     "correct":"The pronoun 'sa' refers to Rama who departed for exile after receiving his father's blessing",
     "partial":["'sa' could refer to any male character present"],"partial_idx":[2],
     "tools_needed":["referent_tracker","witness_compare"],
     "options":["The pronoun 'sa' refers to Rama who departed for exile after receiving his father's blessing",
                "'sa' refers to Lakshmana who accompanied Rama",
                "'sa' could refer to any male character present",
                "The verse describes Dasharatha going to the forest"],
     "glossary":{"natvā":[{"meaning":"having bowed","domain":"general","confidence":0.95}]},
     "sandhi":{},"meter":{},"commentary":{},"witness":{},
     "entity":{"sa":["Rāma","Lakṣmaṇa","Daśaratha"],"pitaram":["Daśaratha"]}},

    {"id":"rest_004","diff":1,"source":"Bhagavad Gita 3.27","domain":"philosophy","ptype":"sandhi",
     "iast":"prakṛteḥ kriyamāṇāni guṇaiḥ karmāṇi sarvaśaḥ","dev":"प्रकृतेः क्रियमाणानि गुणैः कर्माणि सर्वशः",
     "gloss":"All actions are performed by the gunas of prakrti",
     "correct":"The compound 'kriyamāṇāni' splits as 'kriya + māṇa + āni' — passive present participle meaning 'being done'",
     "partial":["It is a simple verb form meaning 'doing'"],"partial_idx":[2],
     "tools_needed":["sandhi_parser","meter_checker"],
     "options":["The compound 'kriyamāṇāni' splits as 'kriya + māṇa + āni' — passive present participle meaning 'being done'",
                "The word is an active participle meaning 'the doer of actions'",
                "It is a simple verb form meaning 'doing'",
                "The compound means 'actions that will be done in future'"],
     "glossary":{},"sandhi":{"kriyamāṇāni":[{"split":"kriya + māṇa + āni","rule":"passive participle formation","plausibility_score":0.95},
                                              {"split":"kri + yamāṇa + āni","rule":"alternative root split","plausibility_score":0.3}]},
     "meter":{"kriya + māṇa + āni":{"preserves_meter":True,"meter_name":"anuṣṭubh"},
              "kri + yamāṇa + āni":{"preserves_meter":False,"meter_name":None}},
     "commentary":{"3.27":"Actions are attributed to prakṛti's guṇas, not the Self"},
     "witness":{"3.27":{"witness_a":"kriyamāṇāni","witness_b":"kriyamāṇāni"}},"entity":{}},

    {"id":"rest_005","diff":1,"source":"Arthashastra 2.6","domain":"narrative","ptype":"glossary",
     "iast":"kośo hi rājñaḥ pradhānam aṅgam","dev":"कोशो हि राज्ञः प्रधानम् अङ्गम्",
     "gloss":"The treasury is indeed the chief limb of the king",
     "correct":"'kośa' here means the state treasury (rājakośa), the primary resource for governance",
     "partial":["'kośa' could mean a repository or sheath"],"partial_idx":[1],
     "tools_needed":["lexicon_lookup","commentary_fetch"],
     "options":["'kośa' here means the state treasury (rājakośa), the primary resource for governance",
                "'kośa' could mean a repository or sheath",
                "'kośa' refers to the five sheaths of the self (pañcakośa)",
                "The verse describes military equipment storage"],
     "glossary":{"kośa":[{"meaning":"treasury, state treasury","domain":"arthashastra","confidence":0.95},
                          {"meaning":"sheath, covering","domain":"vedanta","confidence":0.6}]},
     "sandhi":{},"meter":{},"commentary":{"kośa":"Kauṭilya uses kośa specifically for rājakośa"},
     "witness":{"2.6":{"witness_a":"kośo hi","witness_b":"kośo vai"}},"entity":{}},

    {"id":"rest_006","diff":1,"source":"Surya Siddhanta 1.12","domain":"astronomy","ptype":"sandhi",
     "iast":"bhūmermadhyāt sahasrāṃśoḥ khamadhyam upagacchati","dev":"भूमेर्मध्यात् सहस्रांशोः खमध्यम् उपगच्छति",
     "gloss":"From the center of the earth, the thousand-rayed one reaches the mid-sky",
     "correct":"'bhūmermadhyāt' splits as 'bhūmeḥ + madhyāt' via visarga sandhi — 'from the middle of the earth'",
     "partial":["The compound describes a location but the split is unclear"],"partial_idx":[3],
     "tools_needed":["sandhi_parser","meter_checker"],
     "options":["'bhūmermadhyāt' splits as 'bhūmeḥ + madhyāt' via visarga sandhi — 'from the middle of the earth'",
                "The compound is 'bhūma + ermadhyāt' meaning 'from the great middle'",
                "'bhūmer + madhyāt' is a tatpuruṣa meaning 'earth-center'",
                "The compound describes a location but the split is unclear"],
     "glossary":{},"sandhi":{"bhūmermadhyāt":[{"split":"bhūmeḥ + madhyāt","rule":"visarga sandhi","plausibility_score":0.95},
                                                {"split":"bhūma + ermadhyāt","rule":"invalid","plausibility_score":0.05}]},
     "meter":{"bhūmeḥ + madhyāt":{"preserves_meter":True,"meter_name":"anuṣṭubh"},
              "bhūma + ermadhyāt":{"preserves_meter":False,"meter_name":None}},
     "commentary":{},"witness":{"1.12":{"witness_a":"bhūmermadhyāt","witness_b":"bhūmeḥ madhyāt"}},"entity":{}},

    {"id":"rest_007","diff":2,"source":"Bhagavad Gita 4.7","domain":"philosophy","ptype":"glossary",
     "iast":"yadā yadā hi dharmasya glānir bhavati bhārata","dev":"यदा यदा हि धर्मस्य ग्लानिर्भवति भारत",
     "gloss":"Whenever there is a decline of dharma, O Bharata",
     "correct":"'glāniḥ' signifies a systemic decline or decay of cosmic order, not merely individual moral failure",
     "partial":["'glāniḥ' means weakness or fatigue"],"partial_idx":[1],
     "tools_needed":["lexicon_lookup","commentary_fetch"],
     "options":["'glāniḥ' signifies a systemic decline or decay of cosmic order, not merely individual moral failure",
                "'glāniḥ' means weakness or fatigue",
                "The word refers to physical illness of dharma personified",
                "'glāniḥ' is a synonym for destruction (vināśa)"],
     "glossary":{"glāniḥ":[{"meaning":"decline, decay of order","domain":"philosophy","confidence":0.9},
                             {"meaning":"weakness, fatigue","domain":"general","confidence":0.6}]},
     "sandhi":{},"meter":{},"commentary":{"glāniḥ":"Śaṅkara: decline of dharma means the waning of varṇāśrama order"},
     "witness":{"4.7":{"witness_a":"glānir bhavati","witness_b":"hānir bhavati"}},"entity":{}},

    {"id":"rest_008","diff":2,"source":"Sushruta Samhita 4.3","domain":"ayurveda","ptype":"sandhi",
     "iast":"vātapittakaphaś caiva tridoṣā iti saṃjñitāḥ","dev":"वातपित्तकफश्चैव त्रिदोषा इति संज्ञिताः",
     "gloss":"Vata, Pitta, and Kapha — these are known as the three doshas",
     "correct":"'vātapittakaphaś' splits as 'vāta + pitta + kaphaḥ + ca + eva' — a dvandva compound listing the three doṣas",
     "partial":["It is a simple list of three terms"],"partial_idx":[2],
     "tools_needed":["sandhi_parser","meter_checker"],
     "options":["'vātapittakaphaś' splits as 'vāta + pitta + kaphaḥ + ca + eva' — a dvandva compound listing the three doṣas",
                "The compound means 'the wind-bile-phlegm' as a single entity",
                "It is a simple list of three terms",
                "The word is a bahuvrīhi meaning 'one who has vāta, pitta, and kapha'"],
     "glossary":{},"sandhi":{"vātapittakaphaś":[{"split":"vāta + pitta + kaphaḥ + ca + eva","rule":"dvandva + visarga sandhi","plausibility_score":0.95},
                                                  {"split":"vātapitta + kaphaś","rule":"partial split","plausibility_score":0.3}]},
     "meter":{"vāta + pitta + kaphaḥ + ca + eva":{"preserves_meter":True,"meter_name":"anuṣṭubh"},
              "vātapitta + kaphaś":{"preserves_meter":True,"meter_name":"anuṣṭubh"}},
     "commentary":{},"witness":{"4.3":{"witness_a":"vātapittakaphaś","witness_b":"vātapittaśleshmaś"}},"entity":{}},

    {"id":"rest_009","diff":2,"source":"Ramayana 5.1","domain":"narrative","ptype":"coherence",
     "iast":"hanūmān sāgaraṃ tīrtvā laṅkāṃ prāpya sa vānaraḥ","dev":"हनूमान् सागरं तीर्त्वा लङ्कां प्राप्य स वानरः",
     "gloss":"Hanuman, having crossed the ocean and reached Lanka, that monkey...",
     "correct":"'sa vānaraḥ' is a resumptive pronoun referring back to Hanūmān — emphasizing his identity as the heroic monkey",
     "partial":["'sa' is a generic demonstrative"],"partial_idx":[3],
     "tools_needed":["referent_tracker","witness_compare"],
     "options":["'sa vānaraḥ' is a resumptive pronoun referring back to Hanūmān — emphasizing his identity as the heroic monkey",
                "'sa' refers to Sugriva who sent Hanuman",
                "The verse describes a different monkey warrior",
                "'sa' is a generic demonstrative"],
     "glossary":{},"sandhi":{},"meter":{},"commentary":{},
     "witness":{"5.1":{"witness_a":"sa vānaraḥ","witness_b":"mahāvīraḥ"}},
     "entity":{"sa":["Hanūmān","Sugrīva","Aṅgada"],"vānaraḥ":["monkey warrior"]}},

    {"id":"rest_010","diff":3,"source":"Bhagavad Gita 13.2","domain":"philosophy","ptype":"glossary",
     "iast":"kṣetrajñaṃ cāpi māṃ viddhi sarvakṣetreṣu bhārata","dev":"क्षेत्रज्ञं चापि मां विद्धि सर्वक्षेत्रेषु भारत",
     "gloss":"Know Me also as the Knower of the Field in all fields, O Bharata",
     "correct":"'kṣetrajña' is the conscious principle (ātman/puruṣa) that knows the body-field — Krishna identifies himself with this universal knower",
     "partial":["'kṣetrajña' means the owner of the land"],"partial_idx":[2],
     "tools_needed":["lexicon_lookup","commentary_fetch"],
     "options":["'kṣetrajña' is the conscious principle (ātman/puruṣa) that knows the body-field — Krishna identifies himself with this universal knower",
                "'kṣetrajña' refers to the individual soul only, not the supreme",
                "'kṣetrajña' means the owner of the land",
                "The verse describes agricultural knowledge"],
     "glossary":{"kṣetrajña":[{"meaning":"knower of the field, conscious principle","domain":"vedanta","confidence":0.95},
                               {"meaning":"landowner","domain":"general","confidence":0.3}]},
     "sandhi":{},"meter":{},"commentary":{},
     "witness":{"13.2":{"witness_a":"kṣetrajñaṃ cāpi","witness_b":"kṣetrajñaṃ ca api"}},
     "entity":{"māṃ":["Kṛṣṇa","Paramātman"],"kṣetrajña":["ātman","jīva"]}},

    {"id":"rest_011","diff":3,"source":"Surya Siddhanta 2.1","domain":"astronomy","ptype":"sandhi",
     "iast":"madhyamaṃ ravicandrāṇāṃ sphuṭaṃ kurvan vidhānataḥ","dev":"मध्यमं रविचन्द्राणां स्फुटं कुर्वन् विधानतः",
     "gloss":"Making the mean positions of the sun and moon true, according to rule",
     "correct":"'ravicandrāṇāṃ' splits as 'ravi + candrāṇām' — genitive plural dvandva meaning 'of the sun and moons/planets'",
     "partial":["It means 'of the sun-moon' as a single compound"],"partial_idx":[1],
     "tools_needed":["sandhi_parser","meter_checker"],
     "options":["'ravicandrāṇāṃ' splits as 'ravi + candrāṇām' — genitive plural dvandva meaning 'of the sun and moons/planets'",
                "It means 'of the sun-moon' as a single compound",
                "The word is a tatpuruṣa meaning 'the moon of the sun'",
                "'ravicandrāṇāṃ' is an avyayībhāva compound"],
     "glossary":{},"sandhi":{"ravicandrāṇāṃ":[{"split":"ravi + candrāṇām","rule":"dvandva compound","plausibility_score":0.9}]},
     "meter":{"ravi + candrāṇām":{"preserves_meter":True,"meter_name":"anuṣṭubh"}},
     "commentary":{},"witness":{"2.1":{"witness_a":"ravicandrāṇāṃ","witness_b":"ravīndūnāṃ"}},"entity":{}},

    {"id":"rest_012","diff":3,"source":"Sushruta Samhita 6.1","domain":"ayurveda","ptype":"coherence",
     "iast":"sa vaidyaḥ rogaṃ jñātvā cikitsāṃ kuryāt","dev":"स वैद्यः रोगं ज्ञात्वा चिकित्सां कुर्यात्",
     "gloss":"That physician, having known the disease, should perform treatment",
     "correct":"'sa vaidyaḥ' refers to the skilled physician (prāpta-śāstra) who must diagnose before treating",
     "partial":["'sa' refers to any healer"],"partial_idx":[2],
     "tools_needed":["referent_tracker","witness_compare"],
     "options":["'sa vaidyaḥ' refers to the skilled physician (prāpta-śāstra) who must diagnose before treating",
                "'sa' refers to the patient who must know his disease",
                "'sa' refers to any healer",
                "The verse describes self-treatment"],
     "glossary":{},"sandhi":{},"meter":{},"commentary":{},
     "witness":{"6.1":{"witness_a":"sa vaidyaḥ","witness_b":"sa cikitsakaḥ"}},
     "entity":{"sa":["vaidya (physician)","rogi (patient)"],"rogaṃ":["vyādhi","āmaya"]}},

    {"id":"rest_013","diff":0,"source":"Bhagavad Gita 2.47","domain":"philosophy","ptype":"sandhi",
     "iast":"karmaṇy evādhikāras te mā phaleṣu kadācana","dev":"कर्मण्येवाधिकारस्ते मा फलेषु कदाचन",
     "gloss":"Your right is to action alone, never to its fruits",
     "correct":"'karmaṇy evādhikāras' splits as 'karmaṇi + eva + adhikāraḥ' — locative + emphatic + nominative via sandhi",
     "partial":["The compound simply means 'right to work'"],"partial_idx":[2],
     "tools_needed":["sandhi_parser","meter_checker"],
     "options":["'karmaṇy evādhikāras' splits as 'karmaṇi + eva + adhikāraḥ' — locative + emphatic + nominative via sandhi",
                "'karmaṇyeva' is a single word meaning 'work-only'",
                "The compound simply means 'right to work'",
                "The split is 'karma + ṇyeva + adhikāraḥ'"],
     "glossary":{},"sandhi":{"karmaṇyevādhikāras":[
         {"split":"karmaṇi + eva + adhikāraḥ","rule":"locative sandhi + vowel coalescence","plausibility_score":0.95},
         {"split":"karma + ṇyeva + adhikāraḥ","rule":"invalid","plausibility_score":0.05}]},
     "meter":{"karmaṇi + eva + adhikāraḥ":{"preserves_meter":True,"meter_name":"anuṣṭubh"},
              "karma + ṇyeva + adhikāraḥ":{"preserves_meter":False,"meter_name":None}},
     "commentary":{"2.47":"Śaṅkara: your adhikāra is only in performing action, not in desiring results"},
     "witness":{},"entity":{}},

    {"id":"rest_014","diff":1,"source":"Ramayana 1.2","domain":"narrative","ptype":"coherence",
     "iast":"ko nv asmin sāmprataṃ loke guṇavān kaś ca vīryavān","dev":"को न्वस्मिन् साम्प्रतं लोके गुणवान् कश्च वीर्यवान्",
     "gloss":"Who in this world today is virtuous and who is valorous?",
     "correct":"Vālmīki asks Nārada about the ideal man — the two 'kaḥ' pronouns seek a single person embodying both guṇa and vīrya",
     "partial":["The verse asks about two different people"],"partial_idx":[1],
     "tools_needed":["referent_tracker","witness_compare"],
     "options":["Vālmīki asks Nārada about the ideal man — the two 'kaḥ' pronouns seek a single person embodying both guṇa and vīrya",
                "The verse asks about two different people",
                "The pronouns refer to gods, not humans",
                "'kaḥ' is rhetorical and expects no answer"],
     "glossary":{},"sandhi":{},"meter":{},"commentary":{"1.2":"This is the praśna that initiates the entire Rāmāyaṇa"},
     "witness":{"1.2":{"witness_a":"guṇavān kaś ca","witness_b":"guṇavān ko'pi"}},"entity":{"kaḥ":["Rāma","ideal person"],"asmin loke":["this world"]}},

    {"id":"rest_015","diff":3,"source":"Arthashastra 7.1","domain":"narrative","ptype":"glossary",
     "iast":"ṣāḍguṇyaṃ rājñāṃ pradhānaṃ sādhanaṃ vijaye","dev":"षाड्गुण्यं राज्ञां प्रधानं साधनं विजये",
     "gloss":"The sixfold policy is the chief instrument of kings for victory",
     "correct":"'ṣāḍguṇya' refers to the six measures of foreign policy: sandhi, vigraha, yāna, āsana, dvaidha, saṃśraya",
     "partial":["'ṣāḍguṇya' means six virtues"],"partial_idx":[1],
     "tools_needed":["lexicon_lookup","commentary_fetch"],
     "options":["'ṣāḍguṇya' refers to the six measures of foreign policy: sandhi, vigraha, yāna, āsana, dvaidha, saṃśraya",
                "'ṣāḍguṇya' means six virtues",
                "The word describes six types of military formations",
                "'ṣāḍguṇya' refers to the six seasons relevant to warfare"],
     "glossary":{"ṣāḍguṇya":[{"meaning":"sixfold policy (sandhi, vigraha, yāna, āsana, dvaidha, saṃśraya)","domain":"arthashastra","confidence":0.95},
                               {"meaning":"six qualities","domain":"general","confidence":0.4}]},
     "sandhi":{},"meter":{},"commentary":{},
     "witness":{"7.1":{"witness_a":"ṣāḍguṇyaṃ rājñāṃ","witness_b":"ṣāḍguṇyaṃ nṛpāṇāṃ"}},"entity":{}}
]

def build_episode(raw):
    d = DIFF[raw["diff"]]
    ep = {
        "id": raw["id"],
        "difficulty": d["d"],
        "source": raw["source"],
        "domain": raw["domain"],
        "passage_iast": raw["iast"],
        "passage_devanagari": raw["dev"],
        "passage_english_gloss": raw["gloss"],
        "ocr_noise_level": d["noise"],
        "primary_disambiguation_type": raw["ptype"],
        "correct_answer": raw["correct"],
        "partial_credit_answers": raw["partial"],
        "tool_budget": d["budget"],
        "tools_needed": raw["tools_needed"],
        "glossary_data": raw["glossary"],
        "sandhi_data": raw["sandhi"],
        "meter_data": raw["meter"],
        "commentary_data": raw["commentary"] if d["commentary_pct"] > 0 else {},
        "witness_data": raw["witness"] if d["witnesses"] > 0 else {},
        "entity_map": raw["entity"],
        "candidate_options": raw["options"],
        "partial_credit_indices": raw["partial_idx"],
    }
    if d["noise"] > 0:
        ep["passage_iast_noisy"] = ocr_noise(raw["iast"], d["noise"], hash(raw["id"]))
    return ep

episodes = [build_episode(r) for r in EPISODES_RAW]
data = {"task": "manuscript_restoration", "version": "2.0.0", "episodes": episodes}

out = os.path.join(os.path.dirname(__file__), "..", "data", "task5_restoration.json")
with open(out, "w", encoding="utf-8") as f:
    json.dump(data, f, indent=2, ensure_ascii=False)
print(f"Generated {len(episodes)} episodes -> {out}")
